name: Refresh GitHub Stats Site

on:
  schedule:
    - cron: "15 5 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libcurl4-openssl-dev

      - name: Configure CMake
        run: cmake -S c -B build

      - name: Build site generator
        run: cmake --build build --config Release

      - name: Generate website
        env:
          GITHUB_USERNAME: Jskeen5822
          GITHUB_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
          GH_STATS_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        run: ./build/github_stats

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n $(git status --porcelain docs/index.html) ]]; then
            git add docs/index.html
            git commit -m "chore: refresh GitHub stats"
            git push
          else
            echo "No site changes detected"
          fi
