name: Refresh GitHub Stats Site

on:
  schedule:
    - cron: "15 5 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-site:
    runs-on: ubuntu-latest
    env:
      GITHUB_USERNAME: Jskeen5822
      GH_STATS_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate website
        run: python scripts/update_site.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n $(git status --porcelain docs/index.html) ]]; then
            git add docs/index.html
            git commit -m "chore: refresh GitHub stats"
            git push
          else
            echo "No site changes detected"
          fi
